services:
  - postgres:latest
before_script:
  - gem install bundle --no-ri --no-rdoc
  - bundle install --jobs $(nproc) --path vendor/
  - cp config/database-ci.yml config/database.yml
  - "bundle exec rake db:create RAILS_ENV=test"
  - "RAILS_ENV=test bundle exec rake db:migrate:reset"
rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
